# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-20 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=32)),
                ('port', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HostAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_admin', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_group', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='HostStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_status', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='host_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web01.HostAdmin'),
        ),
        migrations.AddField(
            model_name='host',
            name='host_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web01.HostGroup'),
        ),
        migrations.AddField(
            model_name='host',
            name='host_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web01.HostStatus'),
        ),
    ]
