# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=30)),
                ('port', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('business', models.CharField(max_length=30)),
            ],
        ),
    ]
