# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20171030_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(max_length=64, verbose_name='站点名'),
        ),
    ]
