# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web01', '0005_auto_20170817_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=24)),
                ('port', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HostAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=32)),
                ('host', models.ManyToManyField(to='web01.Host')),
            ],
        ),
        migrations.AlterField(
            model_name='favour',
            name='article_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web01.Article'),
        ),
    ]
