# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web01', '0006_auto_20170817_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favour',
            name='article_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web01.Article'),
        ),
        migrations.AlterField(
            model_name='host',
            name='port',
            field=models.IntegerField(),
        ),
    ]
