# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web01', '0008_auto_20170817_1647'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=24)),
                ('port', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HostAdmin1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='HostRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web01.Host1')),
                ('c2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web01.HostAdmin1')),
            ],
        ),
        migrations.AlterField(
            model_name='favour',
            name='article_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web01.Article'),
        ),
        migrations.AddField(
            model_name='hostadmin1',
            name='host',
            field=models.ManyToManyField(through='web01.HostRelation', to='web01.Host1'),
        ),
    ]
