# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(default='zexiong@huawei.com', max_length=32),
        ),
    ]
