# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_userinfo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='email2',
            field=models.EmailField(default='zexiong@huawei.com', max_length=32),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=32, null=True),
        ),
    ]
