# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20170714_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='upload'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, protocol='ipv4'),
        ),
    ]
