# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20170714_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HostIP', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='HostColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid', models.ImageField(unique=True, upload_to=b'')),
                ('HostColor', models.CharField(max_length=32)),
                ('HostTest', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='HostType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HostType', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='HostColor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.HostColor', to_field='nid'),
        ),
        migrations.AddField(
            model_name='host',
            name='HostType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.HostType'),
        ),
    ]
