# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-15 12:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0006_auto_20170715_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='IsLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islogin', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='User2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='islogin',
            name='user2_and_islogin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.User2'),
        ),
    ]
