# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-16 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_usergroupnew_usernew'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vip', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='usergroupnew',
            name='vip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.Vip'),
        ),
    ]
