# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='interval',
            field=models.IntegerField(default=60, verbose_name='\u76d1\u63a7\u95f4\u9694'),
        ),
    ]
