# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-18 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auto_20170922_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='triggers',
            field=models.ManyToManyField(blank=True, help_text='\u60f3\u8ba9\u54ea\u4e9btrigger\u89e6\u53d1\u5f53\u524d\u62a5\u8b66\u52a8\u4f5c', to='monitor.Trigger'),
        ),
    ]
