# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-01 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsedIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('ip', models.GenericIPAddressField()),
                ('mac', models.CharField(blank=True, max_length=32, null=True)),
                ('os_type', models.CharField(blank=True, max_length=32, null=True)),
                ('hostname', models.CharField(blank=True, max_length=32, null=True)),
                ('createtime', models.CharField(max_length=32)),
                ('createtime_timestamp', models.CharField(max_length=32)),
                ('sql_createtime', models.DateField(auto_now=True)),
                ('utime', models.DateField(auto_now_add=True)),
                ('interface', models.CharField(blank=True, max_length=16, null=True)),
                ('network', models.CharField(blank=True, max_length=32, null=True)),
                ('open_port', models.CharField(blank=True, max_length=256, null=True)),
                ('url', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(blank=True, default='使用中', max_length=16, null=True)),
                ('content', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='usedip',
            unique_together=set([('ip', 'mac')]),
        ),
    ]
