# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-02 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipop_zx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedip',
            name='network',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
