# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-03 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipop_zx', '0002_auto_20180402_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedip',
            name='group',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
