# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-05 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipop_zx', '0003_usedip_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedip',
            name='make',
            field=models.GenericIPAddressField(default=1),
            preserve_default=False,
        ),
    ]
