# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-05 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipop_zx', '0004_usedip_make'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usedip',
            old_name='make',
            new_name='mask',
        ),
    ]
