# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-05 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipop_zx', '0006_remove_usedip_mask'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedip',
            name='mask',
            field=models.GenericIPAddressField(default='255.255255.0'),
        ),
        migrations.AddField(
            model_name='usedip',
            name='password',
            field=models.CharField(default='None', max_length=32),
        ),
        migrations.AddField(
            model_name='usedip',
            name='username',
            field=models.CharField(default='None', max_length=16),
        ),
    ]
