# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-05 13:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipop_zx', '0010_auto_20180405_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedip',
            name='mongo_password',
            field=models.CharField(default='None', max_length=16),
        ),
        migrations.AddField(
            model_name='usedip',
            name='mongo_username',
            field=models.CharField(default='None', max_length=16),
        ),
        migrations.AddField(
            model_name='usedip',
            name='mysql_password',
            field=models.CharField(default='None', max_length=16),
        ),
        migrations.AddField(
            model_name='usedip',
            name='mysql_username',
            field=models.CharField(default='None', max_length=16),
        ),
        migrations.AddField(
            model_name='usedip',
            name='other_password',
            field=models.CharField(default='None', max_length=16),
        ),
        migrations.AddField(
            model_name='usedip',
            name='other_username',
            field=models.CharField(default='None', max_length=16),
        ),
        migrations.AddField(
            model_name='usedip',
            name='url2',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='usedip',
            name='url3',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='usedip',
            name='url4',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='usedip',
            name='url5',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
