# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-07 13:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipop_zx', '0011_auto_20180405_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedip',
            name='mongo_password',
            field=models.CharField(blank=True, default='None', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='usedip',
            name='mongo_username',
            field=models.CharField(blank=True, default='None', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='usedip',
            name='mysql_password',
            field=models.CharField(blank=True, default='None', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='usedip',
            name='mysql_username',
            field=models.CharField(blank=True, default='None', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='usedip',
            name='other_password',
            field=models.CharField(blank=True, default='None', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='usedip',
            name='other_username',
            field=models.CharField(blank=True, default='None', max_length=16, null=True),
        ),
    ]
