# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-07 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipop_zx', '0013_auto_20180407_2247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedip',
            name='password',
            field=models.CharField(blank=True, default='None', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='usedip',
            name='username',
            field=models.CharField(blank=True, default='None', max_length=16, null=True),
        ),
    ]
