# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-13 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipop_zx', '0015_auto_20180413_1330'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usedip',
            unique_together=set([('ip', 'mac')]),
        ),
    ]
