# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-16 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipop_zx', '0024_auto_20180416_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historyip',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usedip',
            name='status',
            field=models.CharField(default='使用中', max_length=16),
        ),
    ]
