# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
