# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20170720_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='head_img',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
    ]
