# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20170720_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='summary',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='head_img',
            field=models.ImageField(null=True, upload_to='static/uploads'),
        ),
    ]
