# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-01 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('pwd', models.CharField(max_length=30)),
                ('memo', models.TextField()),
            ],
        ),
    ]
